### ISSUE TITLE
Full frame rate.  Need at least 1000 fps, 2000-3000 fps would be optimal.

### ISSUE THREAD

**Issue by jebagu** [ThePhage/horse_tornado#2]

**Comment by jebagu** [comment]
Dakami suggested changing speed from 16mhz to 1mhz.  This is done in the eeprom config file.

**Comment by girving** [comment]
2000 works with 4 strips, so it's unlikely that 1000 won't work with 8.  Still need to test.

**Comment by girving** [comment]
eV tested.  Good to go.
